python main.py --config exps/finetune.json
python main.py --config exps/sdlora.json
python main.py --config exps/coda_prompt.json
python main.py --config exps/inflora_c100.json
python main.py --config exps/dualprompt.json
python main.py --config exps/l2p.json
python main.py --config exps/moe_adapters_c100.json
python main.py --config exps/seed_c100.json
python main.py --config exps/hideprompt_c100.json
python main.py --config exps/coscl_c100.json
python main.py --config exps/cpt_c100.json
python main.py --config exps/lfpt5_c100.json
